title: FITS Matching Algorithm
description: The details about FITS and FITS+ algorithms for camera fingerprints matching
show_downloads: fault
google_analytics: G-7DSVNNFSCR

#theme:

theme: jekyll-theme-cayman


